sudo: required

branches:
  only:
  - adding-travis-config

jobs:
  include:
    - stage: test_api
      language: python
      script: cd api && python setup.py pytest
    - stage: test_front
      langauge: node_js
      script: cd front && npm install && npm run build
    - stage: deploy
      script: sh .travis/deploy_dockerhub.sh