sudo: required

matrix:
  include:
    - language: python
      script:
        - cd api && python setup.py pytest

    - language: node_js
      script:
        - cd front && npm install && npm run build && npm run test

after_success:
  - sh .travis/deploy_dockerhub.sh

branches:
  only:
  - adding-travis-config