sudo: required

branches:
  only:
  - adding-travis-config

jobs:
  include:
    - stage: test_api
      language: python
      python: "3.6"
      install: cd api && pip install -r requirements.txt
      script: cd api && python setup.py pytest

    - stage: test_front
      language: node_js
      node_js: stable
      script: cd front && npm test

    - stage: deploy
      script: sh .travis/deploy_dockerhub.sh