sudo: required

branches:
  only:
  - adding-travis-config

jobs:
  include:
    - stage: test
      language: python
      script: cd api && python setup.py pytest
      langauge: node_js
      script: cd front && npm install && npm run build && npm run test
    - stage: deploy
      script: sh .travis/deploy_dockerhub.sh