version: '3'
services:
  web:
     build: ./front
     links:
       - api:api
     ports:
       - "8080:80"

  api:
     build: ./api
     ports:
       - "5000:5000"
     depends_on:
       - redis
     env_file: "./api/configs/dev.env"

  redis:
    image: redis

